filter: ipv6 and linklocal presets

diff --git a/bin/filter b/bin/filter
--- a/bin/filter
+++ b/bin/filter
@@ -144,10 +144,14 @@ while [[ $# -gt 0 ]]; do
         ;;
         -p|--preset)
             shift
-            # add any preset regexes specified
+            # add any specified preset regexes
             case $1 in
-            rfc1918) regexes+=('\b(10\.[0-9]{1,3}|172\.1[6-9]|172\.2[0-9]|172\.3[0-1]|192\.168)\.[0-9]{1,3}\.[0-9]{1,3}\b') ;;
-            ipv4)    regexes+=('\b((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\.)){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\b') ;;
+            rfc1918)    regexes+=('\b(10\.[0-9]{1,3}|172\.1[6-9]|172\.2[0-9]|172\.3[0-1]|192\.168)\.[0-9]{1,3}\.[0-9]{1,3}\b') ;;
+            ipv4)       regexes+=('\b((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\.)){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\b') ;;
+                        # https://stackoverflow.com/a/17871737
+            ipv6)       regexes+=('\b(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))\b') ;;
+                        # 169.254.0.0/16, ffe80::/10
+            linklocal)  regexes+=('\b(169\.254\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))|(fe80:(:[0-9a-fA-F]{0,4}){0,4}(%[0-9a-zA-Z]{1,}){0,1})\b') ;;
             esac
         ;;
         -d|--dir)
@@ -328,6 +332,7 @@ case $grepCmd in
         fi
         # note: xargs causes race conditions with line output; 
         # don't use in parallel because we want to preserve heading order
+        # TODO: save original header and ouput in parallel
     ;;
 esac
 
@@ -353,8 +358,14 @@ fi
 # can I use the --glob builtin to ripgrep and ugrep? grep needs an alternative though
 
 # Other useful presets
-# Multicast, link-local 169.254.
-# \b169\.254\.[0-9]{1,3}\.[0-9]{1,3}\b
+# Multicast 224.0.0.0/4, ff00::/8
+
+# loopback 0.0.0.0/32, 127.0.0.0/8, ::1/128
+
+# Carrier 100.64.0.0/10
+# Address:   100.64.0.0           01100100.01 000000.00000000.00000000
+# Broadcast: 100.127.255.255      01100100.01 111111.11111111.11111111
+
 # local_orig & local_resp
 # ipv4, ipv6, possibly with -o to extract IPs from files
 # ipv4cidr, ipv6cidr
@@ -366,7 +377,7 @@ fi
 # --csv|--header|--keep-lines=1 to pass through header line for csv/tsv logs
 # without ^# to search for this gets back into the original problem
 # could have sed prepend #, grep to include # and then sed to remove it again at the end
-# Use /dev/shm for buffering and compare for performance; Also figure out how to stream output and fail early on | head
+# Use /dev/shm for buffering and compare for performance; Also figure out how to stream output and fail early on | head; trap SIGPIPE
 # Or use read like chop does.
 
 # use \Q and \E instead of escaping periods
@@ -382,3 +393,6 @@ fi
 # similar to --preset, a --find ssl, or --find 'some pattern'
 # maybe make an env varialbe like FILTER_FLAVOR=zeek for working with different types of logs
 # could change whether to search for ^# or not too
+# Read first line and detect if it's a file that exists or not. If it is then assume input is files to search.
+# Wrapper around fd that filters Zeek logs. Filter should call that script as a shortcut.
+# Aliases zconn, zdns, zssl, zhttp, etc. arguments can be directories or further search terms.
